# Reference: https://github.com/langchain-ai/langchain/blob/master/.github/workflows/langchain_release_docker.yml
name: docker-release-omniverse

on:
  workflow_dispatch: # Allows to trigger the workflow manually in GitHub UI
  workflow_call: # Allows triggering from another workflow

jobs:
  release:
    uses: ./.github/workflows/_release_docker.yaml
    with:
      dockerfile: docker/release/release.Dockerfile
      image: omniverse
    secrets: inherit